branches:
  except:
    - /^v[0-9]/

language: node_js

addons:
  postgresql: "9.3"
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
        - gcc-4.8
        - clang

node_js: 'node'

env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"

env:
  global:
    - CXX=g++-4.8

install:
  - npm install --no-shrinkwrap

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config.travis.json config.local.json
  - node server/console.js sequelize:schema:sync

script:
  - npm run lint
  - npm run test:coverage
