language: node_js

addons:
  postgresql: "9.3"
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8

sudo: false

node_js:
  - "stable"
  - "iojs"
  - "4.1"
  - "4.0"

env:
  global:
    - CXX=g++-4.8
    - DSN=postgresql://postgres:@127.0.0.1:5432/travis_ci_test

before_script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
  - node server/console.js sequelize:schema:sync

script:
  - npm run lint
  - npm test
